export default {
  // 基础变量
  'global-bg': '#f3f6f8',
  'global-bg-normal': '#ffffff',
  'base-bg': '#ffffff',
  'base-bg-dark': '#333854',
  brand: '#5e7ce0',
  'brand-foil': '#859bff',
  'brand-hover': '#7693f5',
  'brand-active': '#526ecc',
  'brand-active-focus': '#344899',
  contrast: '#c7000b',
  text: '#252b3a',
  'text-weak': '#575d6c',
  'aide-text': '#8a8e99',
  'aide-text-stress': '#575d6c',
  placeholder: '#8a8e99',
  'light-text': '#ffffff',
  'dark-text': '#252b3a',
  link: '#526ecc',
  'link-active': '#526ecc',
  'link-light': '#96adfa',
  'link-light-active': '#beccfa',
  line: '#adb0b8',
  'dividing-line': '#dfe1e6',
  block: '#ffffff',
  area: '#f8f8f8',
  danger: '#f66f6a',
  warning: '#fac20a',
  waiting: '#9faad7',
  success: '#50d4ab',
  info: '#5e7ce0',
  initial: '#e9edfa',
  unavailable: '#f5f5f6',
  shadow: 'rgba(0, 0, 0, 0.2)',
  'light-shadow': 'rgba(0, 0, 0, 0.1)',
  // 图标
  'icon-text': '#252b3a',
  'icon-bg': '#ffffff',
  'icon-fill': '#d3d5d9',
  'icon-fill-hover': '#adb5ce',
  'icon-fill-active': '#5e7ce0',
  'icon-fill-active-hover': '#526ecc',
  // 表单
  'form-control-line': '#adb0b8',
  'form-control-line-hover': '#575d6c',
  'form-control-line-active': '#5e7ce0',
  'form-control-line-active-hover': '#344899',
  'list-item-active-bg': '#5e7ce0',
  'list-item-active-text': '#ffffff',
  'list-item-active-hover-bg': '#526ecc',
  'list-item-hover-bg': '#f2f5fc',
  'list-item-hover-text': '#526ecc',
  'list-item-selected-bg': '#e9edfa',
  'list-item-strip-bg': '#f2f5fc',
  // 禁用
  'disabled-bg': '#f5f5f6',
  'disabled-line': '#dfe1e6',
  'disabled-text': '#adb0b8',
  'primary-disabled': '#beccfa',
  'icon-fill-active-disabled': '#beccfa',
  // 特殊背景色
  'label-bg': '#eef0f5',
  'connected-overlay-bg': '#ffffff',
  'connected-overlay-line': '#526ecc',
  'fullscreen-overlay-bg': '#ffffff',
  'feedback-overlay-bg': '#464d6e',
  'feedback-overlay-text': '#dfe1e6',
  'embed-search-bg': '#f2f5fc',
  'embed-search-bg-hover': '#eef0f5',
  'float-block-shadow': 'rgba(94, 124, 224, 0.3)',
  'highlight-overlay': 'rgba(255, 255, 255, 0.8)',
  'range-item-hover-bg': '#e9edfa',
  // 按钮
  primary: '#5e7ce0',
  'primary-hover': '#7693f5',
  'primary-active': '#344899',
  'contrast-hover': '#d64a52',
  'contrast-active': '#b12220',
  // 状态
  'danger-line': '#f66f6a',
  'danger-bg': '#ffeeed',
  'warning-line': '#fa9841',
  'warning-bg': '#fff3e8',
  'info-line': '#5e7ce0',
  'info-bg': '#f2f5fc',
  'success-line': '#50d4ab',
  'success-bg': '#edfff9',
  'primary-line': '#5e7ce0',
  'primary-bg': '#f2f5fc',
  'default-line': '#5e7ce0',
  'default-bg': '#f3f6f8',
  // 字体设置相关
  'font-size': '12px',
  'font-size-card-title': '14px',
  'font-size-page-title': '16px',
  'font-size-modal-title': '18px',
  'font-size-price': '20px',
  'font-size-data-overview': '24px',
  'font-size-icon': '16px',
  'font-size-sm': '12px',
  'font-size-md': '12px',
  'font-size-lg': '14px',
  'font-title-weight': 'bold',
  'font-content-weight': 'normal',
  'line-height-base': '1.5',
  // 圆角
  'border-radius': '2px',
  'border-radius-feedback': '4px',
  'border-radius-card': '6px',
  // 阴影
  'shadow-length-base': '0 1px 4px 0',
  'shadow-length-slide-left': '-2px 0 8px 0',
  'shadow-length-slide-right': '2px 0 8px 0',
  'shadow-length-connected-overlay': '0 2px 8px 0',
  'shadow-length-hover': '0 4px 16px 0',
  'shadow-length-feedback-overlay': '0 4px 16px 0',
  'shadow-fullscreen-overlay': '0 8px 40px 0',
  // 动效
  'animation-duration-slow': '300ms',
  'animation-duration-base': '200ms',
  'animation-duration-fast': '100ms',
  'animation-ease-in': 'cubic-bezier(0.5, 0, 0.84, 0.25)',
  'animation-ease-out': 'cubic-bezier(0.16, 0.75, 0.5, 1)',
  'animation-ease-in-out': 'cubic-bezier(0.5, 0.05, 0.5, 0.95)',
  'animation-ease-in-smooth': 'cubic-bezier(0.645, 0.045, 0.355, 1)',
  'animation-linear': 'cubic-bezier(0, 0, 1, 1)',
  // zIndex
  'z-index-full-page-overlay': '1080',
  'z-index-pop-up': '1060',
  'z-index-dropdown': '1052',
  'z-index-modal': '1050',
  'z-index-drawer': '1040',
  'z-index-framework': '1000'
};
